"""Add foreign key constraint for user_id in job_applications table 2

Revision ID: d442a7e45f60
Revises: e925d52975b1
Create Date: 2024-05-24 12:56:18.012418

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d442a7e45f60"
down_revision: Union[str, None] = "e925d52975b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_applications",
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "job_applications", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job_applications", type_="foreignkey")
    op.drop_column("job_applications", "user_id")
    # ### end Alembic commands ###
